import polars
import pprint

# Get counts per (use, detailed_use)
counts = (
    buildings_CAT
    .group_by(["building_space_use_type", "building_space_detailed_use_type"])
    .agg(pl.len().alias("count"))
)

# Compute total per use type
totals = (
    counts
    .group_by("building_space_use_type")
    .agg(pl.col("count").sum().alias("total"))
)

# Join and compute percentages
percentages = (
    counts
    .join(totals, on="building_space_use_type")
    .with_columns(
        (pl.col("count") / pl.col("total") * 100).round(2).alias("percentage")
    )
)

# Convert to nested dictionary
result = {}
for row in percentages.iter_rows(named=True):
    use = row["building_space_use_type"]
    detailed = row["building_space_detailed_use_type"]
    pct = row["percentage"]
    result.setdefault(use, {})[detailed] = pct

pprint.pp(result)
{'Entertainment venues': {'Theater': 5.54,
                          'Restaurant 3 Stars': 0.64,
                          'Entertainment hall': 20.79,
                          'Education': 0.53,
                          'Restaurant 4 Stars': 0.11,
                          'Restaurant 5 Stars': 0.11,
                          'Commerce': 1.39,
                          'Retail commerce': 4.05,
                          'Warehouse': 2.35,
                          'Urbanization works': 0.11,
                          'Restaurant 1 Star': 0.11,
                          'Museum education': 0.32,
                          'Hotel 1 Star': 0.11,
                          'Cinema': 11.41,
                          'Parking': 31.77,
                          'Office': 2.45,
                          'Cultural house education': 0.32,
                          'Hotel Cafe 3 Stars': 0.11,
                          'Porch (100%)': 0.11,
                          'Basic education': 0.53,
                          'Storage': 7.25,
                          'Sports facilities': 0.11,
                          'Casino (<20,000)': 0.21,
                          'Entertainment': 8.1,
                          'Hotel': 0.32,
                          'Other office activities': 1.17},
 'Industrial': {'Education': 0.05,
                'Private garden (100%)': 0.03,
                'Other office activities': 5.26,
                'Undeveloped land': 0.14,
                'Bookstore commerce': 0.02,
                'Storage': 16.54,
                'Residence': 0.01,
                'Casino (<20,000)': 0.02,
                'Sports facilities': 0.01,
                'Housing': 0.52,
                'Machinery industry': 35.47,
                'Warehouse': 6.04,
                'Textile industry': 0.01,
                'Commerce': 0.31,
                'Industry': 18.17,
                'Retail commerce': 2.64,
                'Restaurant 3 Stars': 0.04,
                'Public': 0.02,
                'Urbanization works': 0.1,
                'Other uses': 0.03,
                'Furniture commerce': 0.01,
                'Perfumery commerce': 0.02,
                'Metal industry': 0.01,
                'Gas storage': 0.06,
                'Construction industry': 0.02,
                'Government building': 0.24,
                'Supermarket commerce': 0.03,
                'Other dispensary': 0.01,
                'Glass industry': 0.03,
                'Parking': 8.44,
                'Electric industry': 0.54,
                'Porch (100%)': 0.03,
                'Liquid storage tanks': 0.16,
                'Station': 1.17,
                'Water treatment plants': 0.28,
                'Office': 2.07,
                'Silos, solid storage': 0.12,
                'Pharmacy commerce': 0.04,
                'Chemical industry': 0.21,
                'Transformer hut': 0.08,
                'University education': 0.03,
                'Food industry': 0.02,
                'Public town hall (>20,000)': 0.01,
                'Colonnade (50%)': 0.05,
                'Manufacturing industry': 0.85},
 'Cultural': {'Basic education': 12.47,
              'Casino (<20,000)': 0.13,
              'Public': 0.22,
              'Museum education': 4.65,
              'Other office activities': 0.32,
              'Education (Library)': 0.77,
              'Theater': 0.08,
              'University education': 38.13,
              'Daycare': 0.01,
              'Undeveloped land': 0.01,
              'Government building': 0.01,
              'Cinema': 0.04,
              'Auditorium': 0.01,
              'Institute education': 2.05,
              'Porch (100%)': 0.09,
              'Urbanization works': 0.1,
              'Station': 0.03,
              'Religious': 0.36,
              'Jewelry commerce': 0.02,
              'Sports': 0.95,
              'Housing': 0.9,
              'Electric industry': 0.01,
              'Professional education': 0.82,
              'Religious parish': 3.77,
              'Parking': 10.44,
              'Sports facilities': 1.8,
              'Hotel Cafe 1 Star': 0.02,
              'Commerce': 0.23,
              'Swimming pool': 0.23,
              'Furniture commerce': 0.02,
              'Other uses': 0.41,
              'Hospital': 0.01,
              'Industry': 0.05,
              'Public town hall (>20,000)': 0.02,
              'Office': 0.25,
              'Cultural house education': 0.69,
              'Storage': 1.26,
              'Retail commerce': 0.83,
              'Religious chapel': 0.07,
              'Club': 0.05,
              'Machinery industry': 0.01,
              'Clinic': 0.16,
              'Restaurant 1 Star': 0.01,
              'Warehouse': 1.14,
              'Hotel Cafe 3 Stars': 0.02,
              'Pharmacy commerce': 0.02,
              'Hotel': 0.2,
              'Colonnade (50%)': 0.03,
              'Bookstore commerce': 0.04,
              'Sports complex': 0.08,
              'Restaurant 3 Stars': 0.01,
              'Residence': 1.18,
              'Education': 14.74},
 'Offices': {'Hotel 1 Star': 0.08,
             'Religious': 0.01,
             'Auditorium': 0.01,
             "Musician's office": 0.02,
             'Government building': 0.2,
             'Hotel Cafe 1 Star': 0.03,
             'Agent office': 0.01,
             'Office': 24.87,
             'Porch (100%)': 0.02,
             'Colonnade (50%)': 0.08,
             'Education': 0.02,
             'Retail commerce': 2.01,
             'Housing': 0.27,
             'Furniture commerce': 0.01,
             'Club': 0.0,
             'Salesperson office': 0.01,
             "Weaver's office": 0.01,
             'Financial commerce': 0.02,
             'Liquid storage tanks': 0.01,
             'Machinery industry': 0.32,
             'Religious parish': 0.03,
             'Shoe commerce': 0.0,
             'Fabric commerce': 0.01,
             'Medical/Law office': 0.03,
             'Restaurant 3 Stars': 0.07,
             'Automobile commerce': 0.02,
             'Storage': 1.91,
             'Warehouse': 2.61,
             'Other office activities': 51.09,
             'Provincial court': 0.03,
             'Swimming pool': 0.01,
             'Casino (<20,000)': 0.05,
             'Hotel': 0.09,
             'Restaurant 1 Star': 0.03,
             'Clinic': 0.03,
             'Commerce': 0.6,
             'Basic education': 0.01,
             'Industry': 0.46,
             'Bookstore commerce': 0.04,
             'Other provincial union': 0.01,
             'Galleries commerce': 0.02,
             'Station': 0.01,
             'Entertainment hall': 0.02,
             'Petroleum industry': 0.0,
             'Perfumery commerce': 0.01,
             'Gas storage': 0.0,
             'Public town hall (>20,000)': 0.01,
             'Parking': 14.23,
             'Professional education': 0.01,
             'Private garden (100%)': 0.01,
             'Entertainment': 0.02,
             'Jewelry commerce': 0.02,
             'Pharmacy commerce': 0.01,
             'Food industry': 0.01,
             'Sports': 0.02,
             'Hotel 5 Stars': 0.03,
             'Nursing office': 0.0,
             'Theater': 0.03,
             'Supermarket commerce': 0.01,
             'Wood industry': 0.0,
             'Cinema': 0.02,
             'Other uses': 0.08,
             'Sports facilities': 0.03,
             'Sports complex': 0.0,
             'University education': 0.13,
             'Museum education': 0.05,
             'Hotel 3 Stars': 0.0,
             'Urbanization works': 0.03,
             'Water treatment plants': 0.0,
             'Electric industry': 0.03,
             'Manufacturing industry': 0.01},
 'Residential': {'Undeveloped land': 0.0,
                 'Professional education': 0.0,
                 'Residence': 0.02,
                 'Commerce': 0.44,
                 'Daycare': 0.0,
                 'Hotel 1 Star': 0.0,
                 'Restaurant 3 Stars': 0.03,
                 'Wholesale commerce': 0.0,
                 'Museum education': 0.01,
                 'Other uses': 0.02,
                 'Hotel 2 Stars': 0.0,
                 'Bookstore commerce': 0.03,
                 'Printing commerce': 0.0,
                 'Religious parish': 0.01,
                 'Drugstore commerce': 0.0,
                 'Hotel Cafe 1 Star': 0.0,
                 'Sports facilities': 0.01,
                 'Luxury apartments 3 Stars': 0.0,
                 'Supermarket commerce': 0.01,
                 'Furniture commerce': 0.02,
                 'Casino (<20,000)': 0.01,
                 'Public': 0.01,
                 'Parking': 2.43,
                 'Club': 0.0,
                 'Government building': 0.0,
                 'Hostel Standard 1': 0.0,
                 'Religious': 0.0,
                 'Industry': 0.01,
                 'Hotel Cafe 3 Stars': 0.01,
                 'Perfumery commerce': 0.02,
                 'Education (Library)': 0.0,
                 'Hotel': 0.02,
                 'Storage': 0.63,
                 'Other outpatient clinic': 0.0,
                 'Entertainment': 0.0,
                 'Plumbing commerce': 0.0,
                 'Pharmacy commerce': 0.02,
                 'Fabric commerce': 0.0,
                 'Hotel 3 Stars': 0.0,
                 'Swimming pool': 0.09,
                 'Retail commerce': 1.07,
                 'Financial commerce': 0.0,
                 'Electric industry': 0.0,
                 'Colonnade (50%)': 0.02,
                 'Restaurant 2 Stars': 0.0,
                 'Restaurant 4 Stars': 0.0,
                 'Jewelry commerce': 0.02,
                 'Basic education': 0.0,
                 'Parking in a household': 0.0,
                 'Public town hall (>20,000)': 0.0,
                 'Hotel 5 Stars': 0.0,
                 'Watchmaking commerce': 0.0,
                 'Urbanization works': 0.0,
                 'Education': 0.01,
                 'Theater': 0.0,
                 'Restaurant 5 Stars': 0.0,
                 'University education': 0.02,
                 'Religious chapel': 0.0,
                 'Warehouse': 1.8,
                 'Medical/Law office': 0.0,
                 'Entertainment hall': 0.01,
                 'Sports': 0.01,
                 'Hotel 4 Stars': 0.0,
                 'Automobile commerce': 0.0,
                 'Office': 0.1,
                 'Other office activities': 0.16,
                 'Machinery industry': 0.01,
                 'Clinic': 0.0,
                 'Private garden (100%)': 0.01,
                 'Butcher commerce': 0.0,
                 'Porch (100%)': 0.02,
                 'Restaurant 1 Star': 0.02,
                 'Shoe commerce': 0.0,
                 'Covered terrace (100%)': 0.0,
                 'Cinema': 0.0,
                 'Housing': 92.86},
 'Urbanization and landscaping works, undeveloped land': {'Commerce': 0.49,
                                                          'Automobile commerce': 0.04,
                                                          'Office': 0.8,
                                                          'Other office activities': 0.63,
                                                          'Storage': 2.9,
                                                          'Colonnade (50%)': 0.09,
                                                          'Warehouse': 1.07,
                                                          'Private garden (100%)': 0.4,
                                                          'Government building': 1.3,
                                                          'Open terrace (100%)': 0.09,
                                                          'Religious parish': 0.18,
                                                          'Housing': 11.97,
                                                          'Parking': 6.92,
                                                          'Sports': 0.31,
                                                          'Hotel': 0.04,
                                                          'Retail commerce': 2.14,
                                                          'Other uses': 9.96,
                                                          'Industry': 0.85,
                                                          'Urbanization works': 0.4,
                                                          'Swimming pool': 0.04,
                                                          'Undeveloped land': 40.73,
                                                          'Station': 0.04,
                                                          'University education': 0.04,
                                                          'Hotel Cafe 3 Stars': 0.04,
                                                          'Public': 1.83,
                                                          'Entertainment': 0.13,
                                                          'Public town hall (>20,000)': 0.04,
                                                          'Manufacturing industry': 0.04,
                                                          'Museum education': 0.09,
                                                          'Sports facilities': 13.09,
                                                          'Machinery industry': 3.26},
 'Singular building': {'Daycare': 0.06,
                       'Parking': 5.16,
                       'Perfumery commerce': 0.06,
                       'Machinery industry': 0.13,
                       'Public': 26.11,
                       'Office': 4.32,
                       'Education': 0.39,
                       'Other office activities': 4.06,
                       'Storage': 2.06,
                       'Pharmacy commerce': 0.06,
                       'Other outpatient clinic': 0.64,
                       'Museum education': 1.16,
                       'Bookstore commerce': 0.19,
                       'Public courthouse': 0.45,
                       'Public town hall (>20,000)': 1.81,
                       'Basic education': 0.06,
                       'Restaurant 1 Star': 0.06,
                       'Housing': 4.06,
                       'Religious': 0.06,
                       'Public town hall (<20,000)': 1.16,
                       'University education': 0.06,
                       'Swimming pool': 0.06,
                       'Retail commerce': 0.97,
                       'Other uses': 1.1,
                       'Colonnade (50%)': 0.26,
                       'Public delegation': 4.96,
                       'Theater': 0.06,
                       'Government building': 34.88,
                       'Casino (<20,000)': 0.13,
                       'Provincial court': 2.97,
                       'Warehouse': 2.06,
                       'Hotel Cafe 1 Star': 0.13,
                       'Hotel Cafe 3 Stars': 0.26},
 'Healthcare and Charity': {'Swimming pool': 0.28,
                            'Religious parish': 1.98,
                            'Museum education': 0.04,
                            'Entertainment hall': 0.04,
                            'Porch (100%)': 0.1,
                            'Professional education': 0.06,
                            'Basic education': 0.1,
                            'Storage': 2.27,
                            'Warehouse': 2.23,
                            'Sports': 0.1,
                            'Private garden (100%)': 0.02,
                            'Office': 0.02,
                            'Public': 0.02,
                            'Club': 0.2,
                            'Religious chapel': 0.04,
                            'Hotel Cafe 4 Stars': 0.02,
                            'Cinema': 0.04,
                            'Electric industry': 0.04,
                            'Government building': 0.06,
                            'Other uses': 34.83,
                            'Hospital': 3.3,
                            'Retail commerce': 0.75,
                            'Commerce': 0.14,
                            'Machinery industry': 0.02,
                            'Other outpatient clinic': 2.59,
                            'Other sanatorium': 0.49,
                            'Parking': 14.96,
                            'Other rescue facilities': 0.06,
                            'Residence': 8.4,
                            'Furniture commerce': 0.02,
                            'University education': 0.59,
                            'Daycare': 0.83,
                            'Other office activities': 0.59,
                            'Sports facilities': 0.16,
                            'Religious': 0.61,
                            'Clinic': 21.09,
                            'Other dispensary': 1.82,
                            'Education': 0.12,
                            'Silos, solid storage': 0.02,
                            'Housing': 0.95},
 'Religious': {'Education': 1.4,
               'Other office activities': 0.79,
               'Housing': 2.49,
               'Warehouse': 1.52,
               'Porch (100%)': 0.06,
               'Religious': 31.75,
               'Museum education': 0.24,
               'Theater': 0.06,
               'Religious chapel': 0.79,
               'Office': 1.34,
               'Furniture commerce': 0.06,
               'Parking': 1.03,
               'Clinic': 1.58,
               'Storage': 1.95,
               'Casino (<20,000)': 0.85,
               'University education': 3.71,
               'Other uses': 0.36,
               'Sports facilities': 0.3,
               'Public': 0.12,
               'Industry': 0.06,
               'Swimming pool': 0.12,
               'Institute education': 0.18,
               'Bookstore commerce': 0.12,
               'Retail commerce': 1.22,
               'Commerce': 0.43,
               'Religious parish': 47.26,
               'Religious hermitage': 0.18},
 'Sports facilities': {'Residence': 0.78,
                       'Swimming pool': 14.6,
                       'Private garden (100%)': 0.1,
                       'Retail commerce': 2.09,
                       'Entertainment hall': 0.1,
                       'Parking': 0.68,
                       'Storage': 2.98,
                       'Casino (<20,000)': 1.15,
                       'Other office activities': 0.94,
                       'Sports facilities': 34.07,
                       'Porch (100%)': 0.05,
                       'Housing': 2.35,
                       'Supermarket commerce': 0.1,
                       'Other uses': 0.37,
                       'Stadium': 0.99,
                       'Sports complex': 2.15,
                       'Open terrace (100%)': 0.05,
                       'Station': 0.05,
                       'Commerce': 0.26,
                       'Office': 0.63,
                       'Public': 0.52,
                       'Hotel Cafe 1 Star': 0.26,
                       'Warehouse': 1.78,
                       'Restaurant 3 Stars': 0.68,
                       'Undeveloped land': 0.05,
                       'Sports': 25.12,
                       'University education': 3.19,
                       'Urbanization works': 1.1,
                       'Daycare': 0.1,
                       'Religious parish': 0.99,
                       'Jewelry commerce': 0.05,
                       'Colonnade (50%)': 0.26,
                       'Cinema': 0.05,
                       'Clinic': 0.47,
                       'Entertainment': 0.05,
                       'Hotel': 0.1,
                       'Museum education': 0.1,
                       'Basic education': 0.26,
                       'Education': 0.21,
                       'Hotel Cafe 3 Stars': 0.1},
 'Commercial': {'Other uses': 0.02,
                'Bazaar commerce': 0.01,
                'Private garden (100%)': 0.0,
                'Swimming pool': 0.01,
                'Luxury apartments 3 Stars': 0.0,
                'Casino (<20,000)': 0.03,
                'Other dispensary': 0.0,
                'Automobile commerce': 0.08,
                'Housing': 0.07,
                'Plumbing commerce': 0.0,
                'Printing commerce': 0.01,
                'Pharmacy commerce': 0.64,
                'Supermarket commerce': 1.11,
                'Electric industry': 0.0,
                'Commerce': 15.46,
                'Restaurant 4 Stars': 0.0,
                'Retail commerce': 60.74,
                'Basic education': 0.04,
                'Education': 0.01,
                'Sports facilities': 0.03,
                'Government building': 0.0,
                'Personal/Home commerce': 0.01,
                'Public': 0.01,
                'Hotel Cafe 3 Stars': 0.11,
                'Hotel': 0.04,
                'Financial commerce': 0.04,
                'Bookstore commerce': 0.89,
                'Hotel 2 Stars': 0.0,
                'Club': 0.0,
                'Clinic': 0.01,
                'Wholesale commerce': 0.0,
                'University education': 0.02,
                'Hotel 1 Star': 0.05,
                'Metal industry': 0.0,
                'Machinery industry': 0.07,
                'Theater': 0.01,
                'Auditorium': 0.0,
                'Drugstore commerce': 0.01,
                'Parking': 0.52,
                'Urbanization works': 0.0,
                'Jewelry commerce': 0.43,
                'Restaurant 2 Stars': 0.02,
                'Religious parish': 0.0,
                'Shoe commerce': 0.02,
                'Liquid storage tanks': 0.0,
                'Warehouse': 9.67,
                'Butcher commerce': 0.01,
                'Restaurant 1 Star': 0.36,
                'Daycare': 0.0,
                'Restaurant 3 Stars': 0.71,
                'Fabric commerce': 0.06,
                'Perfumery commerce': 0.87,
                'Hotel 3 Stars': 0.01,
                'Entertainment hall': 0.09,
                'Furniture commerce': 1.08,
                'Station': 0.0,
                'Office': 0.82,
                'Other office activities': 2.3,
                'Storage': 2.52,
                'Hotel Cafe 2 Stars': 0.01,
                'Undeveloped land': 0.01,
                'Agent office': 0.0,
                'Religious': 0.0,
                'Hotel Cafe 1 Star': 0.18,
                'Industry': 0.03,
                'Cinema': 0.08,
                'Hotel Cafe 4 Stars': 0.01,
                'Museum education': 0.01,
                'Porch (100%)': 0.0,
                'Galleries commerce': 0.59,
                'Entertainment': 0.02,
                'Sports': 0.01},
 'Leisure and Hospitality': {'Restaurant 1 Star': 0.42,
                             'Hotel Cafe 4 Stars': 0.19,
                             'Hotel Cafe 2 Stars': 0.03,
                             'Jewelry commerce': 0.03,
                             'Hostel Standard 2': 0.36,
                             'Public': 0.03,
                             'Hotel 4 Stars': 9.88,
                             'Sports complex': 0.02,
                             'University education': 0.04,
                             'Furniture commerce': 0.01,
                             'Parking': 14.22,
                             'Other uses': 0.43,
                             'Clinic': 0.01,
                             'Hotel 1 Star': 11.2,
                             'Entertainment hall': 0.02,
                             'Electric industry': 0.05,
                             'Station': 0.05,
                             'Butcher commerce': 0.01,
                             'Restaurant 5 Stars': 0.07,
                             'Hotel 3 Stars': 9.99,
                             'Hotel Cafe 3 Stars': 0.03,
                             'Pharmacy commerce': 0.05,
                             'Retail commerce': 2.97,
                             'Other office activities': 0.66,
                             'Colonnade (50%)': 0.05,
                             'Porch (100%)': 0.03,
                             'Liquid storage tanks': 0.02,
                             'Sports': 0.16,
                             'Museum education': 0.05,
                             'Hotel': 24.08,
                             'Casino (>20,000)': 0.03,
                             'Casino (<20,000)': 5.12,
                             'Sports facilities': 0.05,
                             'Hotel Cafe 1 Star': 0.23,
                             'Urbanization works': 0.05,
                             'Entertainment': 0.54,
                             'Swimming pool': 0.32,
                             'Office': 0.44,
                             'Education (Library)': 0.02,
                             'Hotel 5 Stars': 5.21,
                             'Religious': 0.02,
                             'Theater': 0.03,
                             'Hostel Standard 3': 0.17,
                             'Perfumery commerce': 0.02,
                             'Restaurant 3 Stars': 1.1,
                             'Luxury apartments 3 Stars': 1.25,
                             'Industry': 0.02,
                             'Storage': 1.58,
                             'Luxury apartments 1 Star': 0.36,
                             'Restaurant 2 Stars': 0.12,
                             'Warehouse': 3.55,
                             'Bookstore commerce': 0.09,
                             'Basic education': 0.01,
                             'Covered terrace (100%)': 0.01,
                             'Club': 0.42,
                             'Housing': 0.84,
                             'Education': 0.1,
                             'Hotel 2 Stars': 1.49,
                             'Auditorium': 0.09,
                             'Cinema': 0.12,
                             'Hostel Standard 1': 0.21,
                             'Commerce': 0.66,
                             'Residence': 0.12,
                             'Religious parish': 0.05,
                             'Cultural house education': 0.17,
                             'Supermarket commerce': 0.01,
                             'Restaurant 4 Stars': 0.18,
                             'Hotel Cafe 5 Stars': 0.01},
 'Warehouse - Parking': {'Urbanization works': 0.0,
                         'Office': 0.0,
                         'Metal industry': 0.0,
                         'Hotel': 0.0,
                         'Religious': 0.0,
                         'Parking': 90.06,
                         'Station': 0.0,
                         'Religious parish': 0.01,
                         'Sports facilities': 0.0,
                         'Public town hall (<20,000)': 0.0,
                         'Other dispensary': 0.0,
                         'Transformer hut': 0.0,
                         'Housing': 0.02,
                         'Storage': 3.76,
                         'Retail commerce': 0.0,
                         'Museum education': 0.0,
                         'Warehouse': 5.97,
                         'Basic education': 0.01,
                         'Sports': 0.0,
                         'Electric industry': 0.0,
                         'Porch (100%)': 0.0,
                         'Swimming pool': 0.0,
                         'Education': 0.0,
                         'Commerce': 0.0,
                         'Machinery industry': 0.03,
                         'Parking in a household': 0.01,
                         'Government building': 0.02,
                         'Other uses': 0.01,
                         'Industry': 0.0,
                         'Other office activities': 0.0,
                         'Public delegation': 0.0,
                         'Jewelry commerce': 0.0,
                         'Residence': 0.0,
                         'University education': 0.04,
                         'Other outpatient clinic': 0.0,
                         'Clinic': 0.0,
                         'Public': 0.0,
                         'Undeveloped land': 0.03},
 'Agricultural': {'Parking': 8.33,
                  'Warehouse': 5.56,
                  'Office': 11.11,
                  'Storage': 8.33,
                  'Housing': 41.67,
                  'Retail commerce': 8.33,
                  'Religious': 2.78,
                  'Other uses': 11.11,
                  'Liquid storage tanks': 2.78}}